"""HAN 2026 participant team_21058 (agent id 21058, class MiAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .mi_agent import MiAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21058
NAME = 'MiAgent'
CLASS_NAME = 'MiAgent'
VERSION = '3.12.10'
TEAM = 'Team 365'
AUTHOR = 'Miyu Okada'
MEMBERS = [{'name': 'Miyu Okada', 'institution': 'Kyoto University', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Kyoto University'
TAGS = ['Large Language Model']
USES_LLM = True
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
