"""HAN 2026 participant team_21787 (agent id 21787, class HybridPisaNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .hybridpisa import HybridPisaNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21787
NAME = 'HybridPisaNegotiator'
CLASS_NAME = 'HybridPisaNegotiator'
VERSION = '0.0.1'
TEAM = 'Team 508'
AUTHOR = 'Beste Nur Pacci'
MEMBERS = [{'name': 'Beste Nur Pacci', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Multi-Agent Reinforcement Learning', 'Supervised Learning', 'Bayesian Methods', 'Heuristic / Rule-based', 'Generative AI', 'Large Language Model']
USES_LLM = True
DESC = "HybridPisaNegotiator is a hybrid negotiation agent that combines a classical heuristic bidding strategy with a Bayesian opponent model and an optional LLM dialogue layer. Its bidding follows the Keskin2021 time-based + behavior-based concession scheme: a quadratic Bézier curve sets a target utility over time, blended with an empathy-weighted reaction to the opponent's concession pattern, while detected opponent behavior (competitive/cooperative/silent) adaptively tunes the concession parameters via an exponential moving average. A local LLM (Qwen3-4B via Ollama) generates short, human-sounding messages grounded in the actual offer and scenario context, with templated fallbacks and a circuit breaker so the negotiation never stalls if the model is slow or unavailable."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
