"""HAN 2026 participant team_21687 (agent id 21687, class HAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .hagent_agent import HAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21687
NAME = 'hagent'
CLASS_NAME = 'HAgent'
VERSION = '0.0.1'
TEAM = 'Team 504'
AUTHOR = 'Hrithik Nambiar'
MEMBERS = [{'name': 'Hrithik Nambiar', 'institution': 'Brown University', 'country': 'United States'}]
COUNTRY = 'United States'
INSTITUTION = 'Brown University'
TAGS = ['Game Theory', 'Economics', 'Heuristic / Rule-based']
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
