"""HAN 2026 participant team_21146 (agent id 21146, class T2Agent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .t2agent import T2Agent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21146
NAME = 'T2Agent'
CLASS_NAME = 'T2Agent'
VERSION = '3.14.3'
TEAM = 'Team 397'
AUTHOR = 'TogasakiTakashi'
MEMBERS = [{'name': 'TogasakiTakashi', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Psychology', 'Large Language Model']
USES_LLM = True
DESC = 'T2Agent follows a risk-adaptive, target-guided negotiation strategy. It estimates the opponent’s behavior from bid history, monitors concession pace, volatility, and potential non-concession, then chooses an appropriate mode ranging from firm to cooperative. Instead of relying on a single blended score, it first determines how much utility risk is acceptable, sets a target utility for the current phase, and searches for Pareto or near-Pareto offers around that target. As time pressure increases, it relaxes thresholds carefully while avoiding unnecessary early concessions. Natural-language responses are generated separately from numerical decisions, keeping the strategic bidding logic deterministic, analyzable, and robust across domains and scenarios.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
