"""HAN 2026 participant team_21146 (agent id 21146, class T2Agent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .t2agent import T2Agent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21146
NAME = 'T2Agent'
CLASS_NAME = 'T2Agent'
VERSION = '3.14.3'
TEAM = 'Team 397'
AUTHOR = 'TogasakiTakashi'
MEMBERS = [{'name': 'TogasakiTakashi', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Large Language Model']
USES_LLM = True
DESC = 'RiskAdaptiveV13Negotiator is a risk-adaptive negotiation agent designed for the HAN 2026 setting. The agent combines a deterministic concession strategy with lightweight language-based risk assessment. Its core policy estimates negotiation breakdown risk from time pressure, offer gaps, concession stagnation, and an LLM-based interpretation of the recent dialogue. Both heuristic risk and LLM risk are smoothed with exponential moving averages to avoid unstable one-turn reactions. The final risk value directly controls acceptance thresholds and proposal targets: when risk is low, the agent preserves high self-utility; when risk rises, it concedes more actively to improve agreement chances. Counteroffers are selected from near-Pareto-efficient outcomes close to the current target utility, prioritizing offers that remain acceptable for the agent while appearing attractive to the opponent. The LLM is used only as an auxiliary risk signal, not as the primary decision maker.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
