"""HAN 2026 participant team_22262 (agent id 22262, class SnowyDayV2).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .snowy_day_v2 import SnowyDayV2 as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 22262
NAME = 'SnowyDayAgent'
CLASS_NAME = 'SnowyDayV2'
VERSION = '1.1.1'
TEAM = 'ST'
AUTHOR = 'Tyrone Serapio'
MEMBERS = [{'name': 'Tyrone Serapio', 'institution': 'Brown University', 'country': 'United States'}]
COUNTRY = 'United States'
INSTITUTION = 'Brown University'
TAGS = ['Supervised Learning', 'Heuristic / Rule-based']
USES_LLM = False
DESC = 'We present SnowDay, our submitted agent for the ANAC 2026 Human-Agent Negotiation League. While Large Language Models (LLMs) are useful communicators, they are unreliable strategic decision-makers without additional structure. Our agent makes all decisions based on a lightweight symbolic negotiation policy, using an online classifier to infer the opponent’s behavior style from early offers and select a corresponding offer\r\nstrategy for our agent.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
