"""HAN 2026 participant team_22147 (agent id 22147, class Agent96).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .agent96 import Agent96 as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 22147
NAME = 'Agent96'
CLASS_NAME = 'Agent96'
VERSION = '0.4.98'
TEAM = 'Agent96'
AUTHOR = 'Ismail Kerfai'
MEMBERS = [{'name': 'Ismail Kerfai', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}, {'name': 'Iyed Hammami', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}]
COUNTRY = 'Germany'
INSTITUTION = 'Leibniz Universität Hannover'
TAGS = ['Large Language Model']
USES_LLM = True
DESC = 'Agent96 is a utility-safe hybrid negotiation agent for the HAN 2026 Human-Agent Negotiation League. Its binding negotiation decisions are made by deterministic code: it enumerates the outcome space, protects reservation value, models opponent preferences from observed offers, and selects offers with an adaptive Boulware-style concession policy. The LLM layer is deliberately bounded and is used only for human-facing messages and soft social hints when interaction looks human-like; it is not trusted with offer validity, utility arithmetic, or final acceptance decisions. Agent96 is designed to behave as a steady, cooperative but firm negotiator across automated and human-facing settings, with robust fallbacks when the LLM is unavailable.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
