"""Smoke test for the HAN 2026 participants.

Imports every class registered for this year/track via
`han_agents.registry.get_participants` and asserts each resolves
to a Python class. Regenerated by
scmlweb/python/update_agents_repo.py.
"""
from negmas.helpers import get_class

from han_agents.registry import get_participants


def test_all_participants_resolve():
    paths = get_participants(2026, None)
    if not paths:
        return  # nothing registered yet
    for p in paths:
        cls = get_class(p)
        assert isinstance(cls, type), f"{p} did not resolve to a class"


def test_finalists_subset_of_all():
    all_paths = set(get_participants(2026, None))
    finalists = set(get_participants(2026, None, finalists_only=True))
    winners = set(get_participants(2026, None, winners_only=True))
    assert finalists <= all_paths
    assert winners <= finalists or winners <= all_paths
