"""HAN 2026 participant team_21400 (agent id 21400, class Sun).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .sun import Sun as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21400
NAME = 'Sun'
CLASS_NAME = 'Sun'
VERSION = '0.0.2'
TEAM = 'Team 434'
AUTHOR = 'Uraz Kağan GÜNEŞ'
MEMBERS = [{'name': 'Uraz Kağan GÜNEŞ', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Game Theory', 'Economics', 'Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = 'Sun is a deterministic BOA-based negotiation agent for the Human-Agent Negotiation League. It uses a time-based offering policy, ACNext acceptance, and a frequency-based opponent model. The agent detects scenario structures such as Grocery, Island, and Trade, then applies scenario-specific counter-offer strategies. It keeps early offers firm, gradually relaxes utility thresholds, and uses a deadline safety mechanism to avoid unnecessary no-agreement outcomes. For rigid opponents, it includes special rescue behavior, especially in Grocery-type scenarios. The agent does not rely on an LLM, making it fast, reproducible, and stable during tournament execution.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
