"""HAN 2026 participant team_22286 (agent id 22286, class CloserNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .closer import CloserNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 22286
NAME = 'Closerv23'
CLASS_NAME = 'CloserNegotiator'
VERSION = '0.19.12'
TEAM = 'Team 422'
AUTHOR = 'Avinash Pathak'
MEMBERS = [{'name': 'Avinash Pathak', 'institution': 'Independent', 'country': 'India'}]
COUNTRY = 'India'
INSTITUTION = 'Independent'
TAGS = ['Game Theory', 'Psychology', 'Heuristic / Rule-based', 'Generative AI']
USES_LLM = False
DESC = 'Adaptive fair negotiator, floor 0.40, smart-bounded LLM persuasion, timeout-safe.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
