"""HAN 2026 participant team_21736 (agent id 21736, class Han).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .hi.han import Han as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21736
NAME = 'HiHan'
CLASS_NAME = 'Han'
VERSION = '0.99.96'
TEAM = 'チーム298'
AUTHOR = 'カズマ'
MEMBERS = [{'name': '望月和真', 'institution': None, 'country': None}, {'name': 'カズマ', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Multimodal']
USES_LLM = False
DESC = "The Han agent employs a comprehensive, time-dependent negotiation strategy. Its bidding mechanism utilizes a Boulware-like concession tactic, meaning it concedes very slowly during the initial stages to protect its utility, before conceding more rapidly as the deadline approaches. It maintains a strict reservation value equivalent to ensure profitable agreements. For its acceptance strategy, the Han agent implements an AC_next approach combined with dynamic, time-dependent utility thresholds. It will only accept an opponent's offer if the estimated utility meets or exceeds this dynamically calculated threshold at any given turn. To prevent poor outcomes, it features an absolute minimum threshold to walk away and end the negotiation rather than accept a bad deal at the deadline. Additionally, the agent integrates a sophisticated, multi-modal communication strategy divided into three distinct psychological phases based on time progress. In the early phase (0-30% progress), it generates text focused on anchoring and rapport building. During the middle phase (30-80%), it shifts to logrolling and tit-for-tat language to encourage mutual trade-offs. In the final phase (above 80%), it leverages urgency and closing techniques to secure a deal before time runs out."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
