"""HAN 2026 participant team_21181 (agent id 21181, class AgoraNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .agora import AgoraNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21181
NAME = 'AgoraAINegotiator'
CLASS_NAME = 'AgoraNegotiator'
VERSION = '3.14.3'
TEAM = 'agoraAI'
AUTHOR = 'Christos Tsoufis'
MEMBERS = [{'name': 'Christos Tsoufis', 'institution': 'Université Paris Dauphine - PSL', 'country': 'France'}]
COUNTRY = 'France'
INSTITUTION = 'Université Paris Dauphine - PSL'
TAGS = ['Bayesian Methods', 'Game Theory', 'Search Algorithms', 'Heuristic / Rule-based', 'Optimization', 'Generative AI', 'Large Language Model']
USES_LLM = True
DESC = "Agora is a hybrid agent for the ANAC 2026 Human-Agent Negotiation League. It separates decision-making from wording: a rule-based Boulware core decides every accept, reject, and counter-offer, while a language model only phrases a move the core has already chosen. The opponent model blends a one-shot LLM cold-read of the partner's opening message with a Dirichlet-smoothed estimate of revealed preferences from observed offers. Each counter-offer is picked from four candidates (an opponent-aware band search, a Nash outcome, a Pareto walk, and a precomputed Pareto front) and ranked by an ASTRA-style estimate of the partner's acceptance probability. Acceptance applies eight ordered checks plus a final-step guard. The text layer mirrors the partner's tone, sanitises prompt-injection attempts, and falls back to templates when the model is slow, so the agent always returns a legal move."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
