"""HAN 2026 participant team_21723 (agent id 21723, class HanOmegaNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .han_agent.entry import HanOmegaNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21723
NAME = 'CodexAgentHan'
CLASS_NAME = 'HanOmegaNegotiator'
VERSION = '0.1.0'
TEAM = 'Team 507'
AUTHOR = 'Ryota GENSEKI'
MEMBERS = [{'name': 'Ryota GENSEKI', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Reinforcement Learning']
USES_LLM = False
DESC = 'HanOmegaNegotiator is a non-LLM bilateral negotiation agent designed for the HAN 2026 League. It pre-ranks all rational outcomes, follows an adaptive time-dependent aspiration curve, and selects counteroffers using self-utility, estimated opponent utility, acceptance likelihood, concession efficiency, fairness, and offer proximity. A lightweight frequency model learns preferred values, issue stability, repetition, and concession behavior online. The acceptance policy rejects outcomes below the reservation value and compares each received offer with the utility of the next planned counteroffer using scale-invariant slack. The agent also detects opponents that cycle through previous offers and responds with high-scoring unseen proposals, preventing reciprocal-concession strategies from stalling. After repeated textual rejection, an ordinal anchor search explores alternative compromise dimensions while preserving rationality. Concise template-based messages acknowledge fairness, urgency, and stated needs without revealing private preferences. Deterministic testing across diverse scenarios, opponent families, negotiation roles, and unseen holdout seeds showed improved agreement rate, average normalized utility, and lower-tail robustness.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
