"""HAN 2026 participant team_22270 (agent id 22270, class CivicCompassHANNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .civic_compass import CivicCompassHANNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 22270
NAME = 'CivicHAN'
CLASS_NAME = 'CivicCompassHANNegotiator'
VERSION = '0.0.4'
TEAM = 'Team 409'
AUTHOR = 'Michael Ibrahim'
MEMBERS = [{'name': 'Michael Ibrahim', 'institution': 'Cairo University', 'country': 'Egypt'}]
COUNTRY = 'Egypt'
INSTITUTION = 'Cairo University'
TAGS = ['Game Theory', 'Psychology', 'Search Algorithms', 'Heuristic / Rule-based', 'Optimization', 'Large Language Model']
USES_LLM = True
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
