"""HAN 2026 participant team_21099 (agent id 21099, class Equinox).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .equinox import Equinox as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21099
NAME = 'Equinox'
CLASS_NAME = 'Equinox'
VERSION = '3.11.8'
TEAM = 'Equinox'
AUTHOR = 'Roshia'
MEMBERS = [{'name': 'Roshia', 'institution': 'Kyoto University', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Kyoto University'
TAGS = ['Reinforcement Learning', 'Bayesian Methods', 'Game Theory', 'Economics', 'Large Language Model']
USES_LLM = True
DESC = 'just a starting point for further experimentation.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
