"""HAN 2026 participant team_21399 (agent id 21399, class Group8Negotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .group8 import Group8Negotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21399
NAME = 'Group8'
CLASS_NAME = 'Group8Negotiator'
VERSION = '3.14.4'
TEAM = 'Group_8'
AUTHOR = 'Asim Sallio'
MEMBERS = [{'name': 'Asim Sallio', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Supervised Learning', 'Game Theory']
USES_LLM = False
DESC = "Group8Negotiator is a hybrid agent for the HAN 2026 league. Strategic\r\ndecisions such as accept, reject, and propose are handled by a deterministic core\r\nconsisting of a Boulware time-based bidding strategy, a frequency-based\r\nopponent preference model, and a time- and behavior-adaptive acceptance\r\nthreshold. Natural-language messages are produced by a local\r\nQwen3:4b-instruct language model wrapped around the core through the\r\nLLMMetaNegotiator interface. The agent's novelty is Behavior-Adaptive\r\nPersuasion (BAP): each opponent move is classified using the Hindriks\r\net al. (2011) taxonomy (concession, nice, fortunate, selfish,\r\nunfortunate, silent), the inferred behavior profile (cooperative,\r\ncompetitive, or neutral) is fed into the acceptance threshold, and the\r\nsame profile is injected into the LLM prompt so the message tone adapts\r\nto the opponent's negotiation style. The acceptance threshold is\r\nexpressed as a fraction of the agent's utility range rather than an\r\nabsolute value, which makes the strategy scenario-independent and robust\r\nacross the official Grocery, Island, and Trade scenarios"
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
