"""HAN 2026 participant team_21086 (agent id 21086, class SemrukNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .semruk import SemrukNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21086
NAME = 'Semruk'
CLASS_NAME = 'SemrukNegotiator'
VERSION = '3.14.2'
TEAM = 'Semruk'
AUTHOR = 'Mehmet Tuğberk ÇİL'
MEMBERS = [{'name': 'Mehmet Tuğberk ÇİL', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = []
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
