"""HAN 2026 participant team_21709 (agent id 21709, class AdaptiveBargainNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .submissionhan.adaptive_bargain import AdaptiveBargainNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21709
NAME = 'AdaptiveBargainNegotiator'
CLASS_NAME = 'AdaptiveBargainNegotiator'
VERSION = '0.71.53'
TEAM = 'Team Ukku'
AUTHOR = 'Hajime Endo'
MEMBERS = [{'name': 'Hajime Endo', 'institution': 'Tokyo University of Agriculture and Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Large Language Model']
USES_LLM = True
DESC = 'AdaptiveBargainNegotiator is a hybrid HAN negotiation agent. It uses a BOA-style rule-based negotiation core with time-dependent concession, frequency-based opponent modeling, and adaptive acceptance thresholds, while using an LLM only to generate concise and cooperative natural-language messages. The design aims to preserve reliable formal negotiation behavior while making the interaction understandable and acceptable to human or LLM partners.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
