"""HAN 2026 participant team_21627 (agent id 21627, class NeoNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .neonegotiator import NeoNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21627
NAME = 'NeoNegotiator'
CLASS_NAME = 'NeoNegotiator'
VERSION = '0.13.66'
TEAM = 'Team 377'
AUTHOR = 'Eymen'
MEMBERS = [{'name': 'Eymen', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Supervised Learning', 'Bayesian Methods', 'Psychology', 'Heuristic / Rule-based', 'Symbolic / Logic', 'Large Language Model']
USES_LLM = True
DESC = "NeoNegotiator is a hybrid automated negotiating agent for the HAN 2026 league. It operates in two phases: an interrogation phase that observes the opponent's bidding curve for 15 rounds (with an active Tit-for-Tat probe at round 8), followed by a counter phase that selects one of 13 purpose-built bidding strategies from a 260-entry lookup table indexed by the opponent's Thomas–Kilmann conflict style, emotional state, and detected strategy type. Opponent character is classified from bid-delta analysis across five styles (Competing, Collaborating, Compromising, Avoiding, Accommodating); emotion is detected per round via LLM sentiment classification. A frequency-based opponent preference model enables issue logrolling — finding Pareto-improving outcome swaps at the same utility level. The LLM (qwen3:4b-instruct) generates persuasive text each round using a Tone Matrix that maps the inferred opponent state to a personalised communication directive. Six independently toggleable overlays cover logrolling, sentiment-adaptive tone, door-in-the-face anchoring, BATNA signaling, deadline-delay pressure, and micro-step concessions."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
