"""HAN 2026 participant team_22280 (agent id 22280, class AegisR168FinalNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .aegis_agent_r168 import AegisR168FinalNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 22280
NAME = 'AegisAgentR168'
CLASS_NAME = 'AegisR168FinalNegotiator'
VERSION = '3.13.3'
TEAM = 'Team 374'
AUTHOR = 'Mizuno'
MEMBERS = [{'name': 'Mizuno', 'institution': None, 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = None
TAGS = ['Bayesian Methods', 'Generative AI', 'Large Language Model']
USES_LLM = True
DESC = 'AegisAgent is a rule-based negotiation agent for ANAC 2026 HAN. Its main goal is to reach agreements while keeping strong utility for itself. The agent does not ask an LLM to choose offers or decide whether to accept. Instead, it uses the utility function, negotiation history, time remaining, repeated offers, and the opponent’s messages to estimate what kind of offer may work. It then selects offers by balancing its own utility with the chance that the opponent may accept. The LLM is used only to write short, natural messages. A validation and fallback layer keeps the message consistent with the fixed offer and helps avoid unnecessary breakdowns near the end.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
