"""HAN 2026 participant team_21125 (agent id 21125, class HannariHamaguriHAN).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .hannari_hamaguri_han import HannariHamaguriHAN as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21125
NAME = 'HannariHamaguriHAN'
CLASS_NAME = 'HannariHamaguriHAN'
VERSION = '3.12.3'
TEAM = 'Team 376'
AUTHOR = 'Rinon Asanuma'
MEMBERS = [{'name': 'Rinon Asanuma', 'institution': None, 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Tokyo University of Agriculture and Technology'
TAGS = ['Game Theory', 'Search Algorithms', 'Heuristic / Rule-based']
USES_LLM = False
DESC = 'HannariHamaguriHAN is a deterministic BOA-based HAN negotiator designed for robust, low-latency negotiation without external LLM calls. It combines an ambitious time-dependent offering policy with a conservative acceptance policy that avoids agreements below the reserved value. The agent uses a softened HardHeaded/Smith frequency opponent model to orient offers toward likely acceptable outcomes while preserving high own utility. The submitted version keeps the strong baseline acceptance behavior and selectively expands the offering candidate set in trade-like domains to improve agreement quality without increasing risk in grocery-like or island-like scenarios. Natural-language messages are generated with lightweight templates for stable tournament execution.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
