"""HAN 2026 participant team_21480 (agent id 21480, class GunnerAgent).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .gunner_agent import GunnerAgent as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21480
NAME = 'Gunner_Agent'
CLASS_NAME = 'GunnerAgent'
VERSION = '1'
TEAM = 'Team 372'
AUTHOR = 'Omer Shani Steinmetz'
MEMBERS = [{'name': 'Omer Shani Steinmetz', 'institution': 'College of Management Academic Studies', 'country': 'Israel'}]
COUNTRY = 'Israel'
INSTITUTION = 'College of Management Academic Studies'
TAGS = ['Bayesian Methods', 'Large Language Model']
USES_LLM = True
DESC = "GunnerAgent is a bilateral negotiation agent for the ANAC 2026 HAN League, designed around a clean separation between strategy and presentation. It is built from two layers. The numerical core (GunnerCore) is the decision-maker: it handles all bidding and acceptance logic, choosing what to offer and whether to accept based on a concession strategy and an opponent model learned from the partner's offer history. The LLM wrapper (GunnerAgent) is the communication layer: it takes the move the core has already decided and generates the short natural-language message that accompanies it, adapting tone to the type of move and to the partner's last action. Crucially, the LLM never selects an offer or makes an accept/reject decision — it only phrases what the core has chosen. This separation keeps the strategy reproducible and independently tunable."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
