"""HAN 2026 participant team_21113 (agent id 21113, class NEXUSNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .nexus import NEXUSNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21113
NAME = 'NEXUSNegotiator'
CLASS_NAME = 'NEXUSNegotiator'
VERSION = '3.11.13'
TEAM = 'Team 387'
AUTHOR = 'Shahzeen Ahmad'
MEMBERS = [{'name': 'Shahzeen Ahmad', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Bayesian Methods', 'Game Theory', 'Psychology', 'Heuristic / Rule-based', 'Optimization', 'Generative AI', 'Embeddings / Vector Search']
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
