"""HAN 2026 participant team_21113 (agent id 21113, class NEXUSNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .nexus import NEXUSNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21113
NAME = 'NEXUSNegotiator'
CLASS_NAME = 'NEXUSNegotiator'
VERSION = '3.11.13'
TEAM = 'Team 387'
AUTHOR = 'Shahzeen Ahmad'
MEMBERS = [{'name': 'Shahzeen Ahmad', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Reinforcement Learning', 'Bayesian Methods', 'Game Theory', 'Psychology', 'Heuristic / Rule-based', 'Optimization', 'Generative AI', 'Embeddings / Vector Search']
USES_LLM = False
DESC = 'NEXUS eliminates zero-score deadlocks through a dynamic achievable utility estimator that continuously adapts the aspiration level using five signals: Pareto frontier ceiling, Nash bargaining anchor, empirical best-received offer, opponent behaviour (DANS classification), and RVFitter reservation value estimate. Bidding holds near the utility maximum until t=0.65, then descends via a closed-form Boulware curve that is step-count-invariant. A hybrid three-layer opponent model (frequency, hard-headed, Bayesian Dirichlet) with optional GNash blending estimates opponent preferences. Acceptance uses thirteen graduated conditions including ACnext, Nash-point recognition, and steps-left-based deadline rules. Free-text messages apply lexicon sentiment with a Bayesian manipulation filter to modulate tone.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
