"""HAN 2026 participant team_21656 (agent id 21656, class Nekotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .nekotiator import Nekotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21656
NAME = 'Nekotiator'
CLASS_NAME = 'Nekotiator'
VERSION = '0.29.6'
TEAM = 'Team 390'
AUTHOR = 'Toshikazu Ogura'
MEMBERS = [{'name': 'Toshikazu Ogura', 'institution': 'Nagoya Institute of Technology', 'country': 'Japan'}]
COUNTRY = 'Japan'
INSTITUTION = 'Nagoya Institute of Technology'
TAGS = ['Large Language Model']
USES_LLM = True
DESC = 'This agent is a hybrid negotiation system that blends traditional utility-based reasoning with language model-based opponent modeling. It begins by evaluating its own utility function and then analyzes incoming proposals and text utterances to infer opponent preferences, weights, and likely target values. For zero-sum issues it treats higher values as opponent-favored utility, while for non-zero-sum issues it favors offers near estimated target values. The agent uses a concession schedule that starts high and gradually gives ground, accepts any opponent offer that meets or exceeds its current aspiration or is no worse than the best counter-proposal, and otherwise returns a win-win counteroffer. By integrating LLM preference extraction into candidate scoring, it seeks balanced agreements that respect both self-interest and predicted opponent satisfaction.'
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
