"""HAN 2026 participant team_21049 (agent id 21049, class NegotiatorX).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .negotiatorx.negotiator import NegotiatorX as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21049
NAME = 'NegotiatorX'
CLASS_NAME = 'NegotiatorX'
VERSION = 'X'
TEAM = 'TeamX'
AUTHOR = 'Serhat Giydiren'
MEMBERS = [{'name': 'Serhat Giydiren', 'institution': 'Özyeğin University', 'country': 'Türkiye'}]
COUNTRY = 'Türkiye'
INSTITUTION = 'Özyeğin University'
TAGS = ['Game Theory', 'Psychology', 'Search Algorithms', 'Heuristic / Rule-based', 'Optimization']
USES_LLM = False
DESC = ''
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
