"""HAN 2026 participant team_21405 (agent id 21405, class LastOfferNegotiator).

Generated by scmlweb/python/update_agents_repo.py.
"""
from .lastoffer import LastOfferNegotiator as MAIN_AGENT

__all__ = ["MAIN_AGENT"]

# --- BEGIN generated metadata (scmlweb update_agents_repo.py) ---
ID = 21405
NAME = 'LastOffer'
CLASS_NAME = 'LastOfferNegotiator'
VERSION = '3.0'
TEAM = 'Last Offer'
AUTHOR = 'Felix Bieber'
MEMBERS = [{'name': 'Felix Bieber', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}, {'name': 'Katherina Pukhova', 'institution': 'Leibniz Universität Hannover', 'country': 'Germany'}]
COUNTRY = 'Germany'
INSTITUTION = 'Leibniz Universität Hannover'
TAGS = ['Game Theory', 'Heuristic / Rule-based', 'Large Language Model']
USES_LLM = True
DESC = "The `LastOfferNegotiator` is a hybrid agent combining a mathematical decision engine and a conflict-based opponent model to execute time-based, Boulware-style concessions while proposing offers structurally similar to the opponent's bids. It leverages an LLM to dynamically generate natural, argument-driven text responses."
METADATA = {
    'id': ID, 'name': NAME, 'class_name': CLASS_NAME,
    'version': VERSION, 'team': TEAM, 'author': AUTHOR,
    'members': MEMBERS, 'country': COUNTRY,
    'institution': INSTITUTION, 'tags': TAGS,
    'uses_llm': USES_LLM, 'description': DESC,
}
# --- END generated metadata ---
